# Keep is separated for now. Once done, we will merge it into release workflow
name: Release Wolfi-based image

on:
  workflow_dispatch:
  push:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    name: Build Wolfi-based image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
      - name: Generate snapshot date
        id: snapshot-date
        run: |
          echo ::set-output name=date::$(date -u +%Y%m%d)
          echo ::set-output name=epoch::$(date -u +%s)
        shell: bash

      - uses: actions/checkout@v4

      # setup qemu, install cosign,melange, etc...
      - uses: docker/setup-qemu-action@v2
      - uses: sigstore/cosign-installer@v3.5.0
      - uses: chainguard-dev/actions/setup-melange@main
      - uses: chainguard-dev/actions/melange-keygen@main
      
      - uses: chainguard-dev/actions/melange-build-pkg@e82b4e5ae10182af72972addcb3fedf7454621c8 # latest as of 2024-05-29
        with:
          config: .melange.yaml
          sign-with-key: true # TODO change with permanent key
          signing-key-path: ${{ github.workspace }}/melange.rsa
          # archs: x86_64,aarch64
          archs: x86_64
          
      - uses: chainguard-images/actions/apko-publish@70ef33423618955be903186c527e677a8bc4689b # latest as of 2024-05-29
        id: apko
        with:
          config: .apko.yaml
          tag: ghcr.io/${{ github.repository }}:wolfi-latest
          keyring-append: /github/workspace/melange.rsa.pub
          source-date-epoch: ${{ steps.snapshot-date.outputs.epoch }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - shell: bash
        run: |
          COSIGN_EXPERIMENTAL=true cosign sign ${{ steps.apko.outputs.digest }} --yes
